package com.example.mysocialapp.data

// Every User will have a Unique UserId (generated by Firebase Auth)
data class User (
    val fullName: String = "",
    val email: String = "",
    val about: String = "",
    var profilePic: String = "",
    val followers: MutableList<String> = mutableListOf(),
    val followings: MutableList<String> = mutableListOf(),
    val posts: MutableList<String> = mutableListOf()
)